import * as utils from '../index.js'

export default ({ person }) => [
  'lazy.', 
  'cute.', 
  'nice.', 
  'dumb.', 
  'vibing.', 
  'thinking.', 
  'having a mental breakdown.', 
  'laughing.', 
  'rofling.', 
  'weird.', 
  'poggers!',
  'nothing.',
  'wholesome.',
  'big brain.',
  'smort.',
  'ah.',
  'not cute.',
  'not nice.',
  'not vibing.',
  'not thinking.',
  'in Tidal gang. <a:gang:755710727246970972>',
  'kind of cute but not quite.',
  'dancing.',
  'playing with friends.',
  'is not is pogger :(',
  'trying, but failing to do a simple task.',
  'watching \'The Great Pretender\' on Netflix. (which is a good show btw and you should watch it)',
  'watching Kiss x Sis... yikes!',
  'hentai.',
  'a pervert!!',
  '<insert funny here>',
  'watching vine compilations on YouTube? Wait, didn\'t vine die like... 2 years ago?!',
  'doing something important.',
  'rewatching Boku no Pico.',
  'in the Boku no Hero fandom.',
  'horny.',
  'using the bot to make funny.',
  'Awaiz.',
  'trying to find the funny... oh wait, it doesn\'t exist!',
  'currently',
  'not.',
  'not cute rn >:c',
  'Iron Man.',
  'Awaiz is stupid.',
  'playing Among Us... which is a ripoff of TTT might I ad-',
  'wasting his time chatting in this discord.',
  'is haha its funny becuase i aded too \'is\'.',
  'not very wholesome poggers 100 right now.',
  'gaming. :sunglasses:',
  'g-g-g-g-gu-gu-guh-g-guh-g-',
  'captain obvious.',
  'GIBBBBBBAAAAAAAAAAAYYYYYYYYYYYYYYYYYYYYYYYY',
  'covering up a crime.',
  'sleepwalking.',
  'trying to fix their fucked up sleep schedule.',
  'doing pushups.',
  'doing drugs O-o',
  'giving a Ted Talk.',
  'getting the liquor out of the pantry.',
  'making out with Freddie Mercury.',
  'thinking about their crush/wifey.',
  'cheating on their waifu.',
  'fumbling to get ready for work.',
  'don\'t',
  'getting got get gotted.',
  'browsing instagram and questioning their life choices',
  'busting out the HH.',
  'thinking of something funny to change their discord avatar to.',
  'listening to Lemon Demon/Neil Cicierega.',
  'browsing reddit.',
  'being weird.',
  'very sexy! (added by Zaaer blame him)',
  'stupid.',
  'slozzing.',
  'on deez nuts! Gottem!',
  'dumber than Awaiz.',
  'dying slowly...',
  'Slozzy\'s best friend!',
  'ripping their hair out.',
  'has converted ﷽ 🛐',
  'doing your mom! HAH GOTTEM xDdDDdDdD',
  'trying to remember what they were going to say but can\'t.',
  'Darren IRL. Here is a reference: https://i.imgur.com/2cU9IAx.jpg.',
  'a booli!!',
  'hugging Zaaer.',
  'cum.',
  'gay <:shinobudab:731677282950971443>',
  'this is not fake put your hands behind your back and wait quietly for 10 seconds. The police will be coming in in approx 15 seconds. You can consider your chances of escape futile; so don\'t try it. You will await your trial in a couple days; disgusting weeabo.',
  'about to die. Please pray for them and remember them, they were a horrible person in life but that\'s ok because they\'re going to be dead soon.',
  'a simp.',
  'gay||ming.||',
  `${person}.`,
  `${person}... it's literally their name...`,
  `${utils.general.randomString()} oops`,
  `not ${person}.`,
  `${person}'s best friend!`
]